name:         ngl_viewer
version:      0.0.1
description:  NGL Viewer Dart library
homepage:     https://github.com/molview/ngl-viewer
environment:
  sdk:        '>=2.1.0 <3.0.0'

dependencies:
  js: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any

